# Generated by Django 6.0.1 on 2026-02-14 13:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_alter_student_percentage_alter_student_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='content',
            field=tinymce.models.HTMLField(default=0),
            preserve_default=False,
        ),
    ]
