# Generated by Django 6.0.1 on 2026-02-14 13:15

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0003_student_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
