# Generated by Django 6.0.1 on 2026-02-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0004_alter_student_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='maths',
        ),
    ]
